language: java
jdk:
- oraclejdk8
install: mvn clean package -Pfrontend -DskipTests=true
cache:
  directories:
  - $HOME/.m2
  - src/main/frontend/node_modules
deploy:
  provider: heroku
  api_key:
    secure: i4etqyoe27UuYhOGsxj3vrkEYrM7ya03USEo5G4EbgwcVwSULQAwzX6ndLzwaNJ2UHcImmIm9FO6OVR5QS+tRiM2HUo2GsiZ2ittoafjlDfryF+yT7vMpHn2ijQGdFEieUSKmQL+u7VMaWwVUld6Nso6qc5PO9/G7dj1jTF8lQ8NW5jyahkzH3I17bVvsR53NRNMdIZ9oiFcoA3RJB4UxqXnQL/2DqVhR4nBaxO+PtGd6NlYdLINZTVSnQch73SOz5UM8HkI2DLsJuLy8U1zyPR/ZD0B9SE3FqGNLiYAatMHW+7OHu5qJ5DZyDiyE7qh9kZfrNHSn3ovsffU3CXYq8oJjYSlyaOKB5fDy6doLbcjkNPuSyUPDLyfYFVvWONmwudC41yzjVjarayIhiloW57qoLDr0DkXytGCwlHIePRebWjgohzUUX3F+ZeeDSx5Tf3me28OtbmrdKEZfm8Jiq6wicdxbVNjG53N1cWt/2bGp+dynuhj86XS2/Fa1r/q2vNYIxnnuKlheGSQzVtU8krCrHAmV9O2fbGR1aDx4egJKs56FsUPKt/5s/pqQ2shT3jqNqnB4q3YWjCCZzYi8QilbgoFaGBMC6aZzw9L2bY3TO2I2C3zklJr9ulLF5XtPh1FDkvmwRQjewYYHdvBoa0KZsbOauZLrWG2X1whIvA=
